language: go
go:
  - 1.9.x
env:
  - CC_TEST_REPORTER_ID=6e1b87f79ad425a664a7b826e6af4096519edebc580f6a70f6062dbe9f7273f6
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - go get github.com/axw/gocov/gocov
  - ./cc-test-reporter before-build
intstall:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go test -v -coverprofile=covergrpcserver.out ./grpcserver
  - go test -v -coverprofile=covermodels.out ./models
  - go test -v -coverprofile=coverproviders.out ./providers
  - go test -v -coverprofile=coverservices.out ./services
  - go test -v -coverprofile=coverhelpers.out ./helpers
  - go test -v -coverprofile=c.out ./
after_script:
  - ./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT
