// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token_storage_grpc.proto

/*
Package token_storage_grpc is a generated protocol buffer package.

It is generated from these files:
	token_storage_grpc.proto

It has these top-level messages:
	Token
	TokenRequest
	TokenResponse
*/
package token_storage_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Token struct {
	Value     string   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	UserId    string   `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Lifetime  int32    `protobuf:"varint,3,opt,name=lifetime" json:"lifetime,omitempty"`
	Timestamp int64    `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Scope     []string `protobuf:"bytes,5,rep,name=scope" json:"scope,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Token) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Token) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Token) GetLifetime() int32 {
	if m != nil {
		return m.Lifetime
	}
	return 0
}

func (m *Token) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Token) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

type TokenRequest struct {
	Signature string `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Token     *Token `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TokenRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *TokenRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TokenRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type TokenResponse struct {
	IsOk   bool   `protobuf:"varint,1,opt,name=is_ok,json=isOk" json:"is_ok,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Token  *Token `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *TokenResponse) Reset()                    { *m = TokenResponse{} }
func (m *TokenResponse) String() string            { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()               {}
func (*TokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TokenResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func (m *TokenResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*TokenRequest)(nil), "TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "TokenResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TokenStorageGrpc service

type TokenStorageGrpcClient interface {
	AddToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	FindToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	DropToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type tokenStorageGrpcClient struct {
	cc *grpc.ClientConn
}

func NewTokenStorageGrpcClient(cc *grpc.ClientConn) TokenStorageGrpcClient {
	return &tokenStorageGrpcClient{cc}
}

func (c *tokenStorageGrpcClient) AddToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := grpc.Invoke(ctx, "/TokenStorageGrpc/AddToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStorageGrpcClient) FindToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := grpc.Invoke(ctx, "/TokenStorageGrpc/FindToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStorageGrpcClient) DropToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := grpc.Invoke(ctx, "/TokenStorageGrpc/DropToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TokenStorageGrpc service

type TokenStorageGrpcServer interface {
	AddToken(context.Context, *TokenRequest) (*TokenResponse, error)
	FindToken(context.Context, *TokenRequest) (*TokenResponse, error)
	DropToken(context.Context, *TokenRequest) (*TokenResponse, error)
}

func RegisterTokenStorageGrpcServer(s *grpc.Server, srv TokenStorageGrpcServer) {
	s.RegisterService(&_TokenStorageGrpc_serviceDesc, srv)
}

func _TokenStorageGrpc_AddToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStorageGrpcServer).AddToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TokenStorageGrpc/AddToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStorageGrpcServer).AddToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStorageGrpc_FindToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStorageGrpcServer).FindToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TokenStorageGrpc/FindToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStorageGrpcServer).FindToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStorageGrpc_DropToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStorageGrpcServer).DropToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TokenStorageGrpc/DropToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStorageGrpcServer).DropToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenStorageGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TokenStorageGrpc",
	HandlerType: (*TokenStorageGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToken",
			Handler:    _TokenStorageGrpc_AddToken_Handler,
		},
		{
			MethodName: "FindToken",
			Handler:    _TokenStorageGrpc_FindToken_Handler,
		},
		{
			MethodName: "DropToken",
			Handler:    _TokenStorageGrpc_DropToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token_storage_grpc.proto",
}

func init() { proto.RegisterFile("token_storage_grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x7f, 0xb7, 0x75, 0xfe, 0x76, 0xa0, 0x08, 0x19, 0x04, 0x56, 0xd5, 0x45, 0x94, 0x55,
	0x24, 0x50, 0x16, 0xe5, 0x04, 0x48, 0x08, 0xc4, 0x0a, 0x29, 0xb0, 0x62, 0x13, 0x85, 0xc4, 0x04,
	0x2b, 0x6d, 0x6c, 0x3c, 0x0e, 0x47, 0xe0, 0x12, 0x5c, 0x16, 0xd9, 0xa6, 0x94, 0xb2, 0x40, 0xb0,
	0x8a, 0xde, 0xcb, 0x68, 0xbe, 0xf7, 0xc6, 0xc0, 0xad, 0x6a, 0x45, 0x57, 0xa0, 0x55, 0xa6, 0x6c,
	0x44, 0xd1, 0x18, 0x5d, 0x65, 0xda, 0x28, 0xab, 0x92, 0x57, 0x02, 0xf4, 0xce, 0xfd, 0x64, 0x87,
	0x40, 0x5f, 0xca, 0x65, 0x2f, 0x38, 0x89, 0x49, 0x3a, 0xc9, 0x83, 0x60, 0xc7, 0xf0, 0xbf, 0x47,
	0x61, 0x0a, 0x59, 0xf3, 0x81, 0xf7, 0x23, 0x27, 0xaf, 0x6b, 0x36, 0x83, 0xf1, 0x52, 0x3e, 0x0a,
	0x2b, 0x57, 0x82, 0x0f, 0x63, 0x92, 0xd2, 0xfc, 0x53, 0xb3, 0x39, 0x4c, 0xdc, 0x17, 0x6d, 0xb9,
	0xd2, 0x7c, 0x14, 0x93, 0x74, 0x98, 0x6f, 0x0c, 0x07, 0xc2, 0x4a, 0x69, 0xc1, 0x69, 0x3c, 0x74,
	0x20, 0x2f, 0x92, 0x27, 0xd8, 0xf5, 0x39, 0x72, 0xf1, 0xdc, 0x0b, 0xb4, 0x6e, 0x07, 0xca, 0xa6,
	0x2b, 0x6d, 0x6f, 0xd6, 0x91, 0x36, 0xc6, 0x36, 0x61, 0xf0, 0x9d, 0x30, 0x07, 0xea, 0x0b, 0xfb,
	0x60, 0x3b, 0x8b, 0x28, 0x0b, 0x9b, 0x83, 0x99, 0xdc, 0xc3, 0xf4, 0x83, 0x84, 0x5a, 0x75, 0x28,
	0xd8, 0x01, 0x50, 0x89, 0x85, 0x6a, 0x3d, 0x66, 0x9c, 0x8f, 0x24, 0xde, 0xb4, 0xec, 0x08, 0x22,
	0xb4, 0xa5, 0xed, 0x71, 0xdd, 0x3b, 0xa8, 0x9f, 0x77, 0x2f, 0xde, 0x08, 0xec, 0x7b, 0xe3, 0x36,
	0x9c, 0xfa, 0xca, 0xe8, 0x8a, 0x9d, 0xc0, 0xf8, 0xbc, 0xae, 0xc3, 0x95, 0xa7, 0xd9, 0xd7, 0x96,
	0xb3, 0xbd, 0x6c, 0x2b, 0x4a, 0xf2, 0x8f, 0x9d, 0xc2, 0xe4, 0x52, 0x76, 0x7f, 0x98, 0xbe, 0x30,
	0x4a, 0xff, 0x6e, 0xfa, 0x21, 0xf2, 0x6f, 0x7e, 0xf6, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xd9,
	0x7c, 0x46, 0x0f, 0x02, 0x00, 0x00,
}
